server {
    listen 80;
    server_name blog-bmarques.duckdns.org;

    # 1. Entrega o Frontend (Arquivos estáticos)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy Reverso para o Backend
    # Quando o front chamar /posts, o Nginx desvia para o container 'blog-backend'
    location /posts {
        proxy_pass http://blog-backend:4000/posts;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}